# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balderdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
